### PR TITLE
allow angular 1.2 since not all other packages support 1.3 yet

### PR DESCRIPTION
**Pull request by bdwain**
Since this doesn't seem to require angular 1.3 functionality, it'd be ideal if it supported angular 1.2 as well as 1.3. Some popular angular packages still require 1.2 (notably the [bootstrap angular directives](https://github.com/angular-ui/bootstrap)).

### CODE REVIEW

**Comment by paradox41** [comment]
Does this cause any issues when downloading from Bower? I figure with Bower you could add a resolution if there is a conflict between what the package says it wants and what the main project says it wants.

Is this not happening?

**Comment by bdwain** [comment]
That is what happens when there is a conflict between all of the version requirements. So without this change, if i tried to bower install angular-chartist in a project that requires angular 1.3 (whether on its own or through a dependency), it asks me to choose a version (1.2 or 1.3) of angular. However, choosing an override means I'm explicitly using a version of angular not supported by my project or one of its dependencies, so that could cause bugs if the version is not actually supported. 




My change is just relaxing the version requirements for angular-chartist. It will still use 1.3 if the project allows for it. It will just use 1.2 the project needs 1.2 for whatever reason. 




Alternatively, people who require 1.2 would always have to specify 1.2 as their override version, which works, but isn't ideal. They don't know that 1.2 actually works. That's usually communicated through bower.json.

**Comment by paradox41** [comment]
After doing a little more [research](http://semver.npmjs.com/) it doesn't look like this will be an issue for users of 1.3.

Before I can merge this in though, please follow the [commit conventions](https://github.com/paradox41/angular-chartist.js/blob/master/CONTRIBUTING.md#commit-conventions).

If you want to open another PR or update this one that is fine, whatever is easiest.

**Comment by bdwain** [comment]
I updated the pull request to be up to date with the main repo. I looked at the commit conventions. Running gulp dist has no effect on this change since I just updated a dependency (and still no jshint errors), so I think I did everything. Let me know if there's anything else I need to do.

**Comment by paradox41** [comment]
Sorry, I should have been clearer. I was referring to the actual commit message, which made me realize I was link to the repo instead of the [actual conventions](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md). Your commit should follow the form of `<type>(<scope>): <subject>`

In this case I think it would be fine if you updated the message to be something like `chore(package): Support Angular ^1.2 as a dependency`

Thanks!

**Comment by bdwain** [comment]
Ok it should be good now.

**Comment by paradox41** [comment]
Awesome! Thanks a lot.

**Pull request merged**
