### PR TITLE
Similar to issue #80

### PR DESCRIPTION
**Pull request by xaralis**
This is similar to issue #80 only for events which happened to have same problem too.

### CODE REVIEW

**Comment by paradox41** [comment]
So these only get picked up for the initial render of the chart? If these change after the fact the chart will neither re-render or get updated since `render` only gets called [when there is no chart or the chart type changes](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L60).

This behavior feels a little odd to me. But perhaps there is no need?

**Comment by xaralis** [comment]
@paradox41 Yes, this is only for the initial rendering.

**Comment by paradox41** [comment]
I cut this release just under `4.0.0-beta.2`. Please use `npm install angular-chartist.js@next`

**Comment by xaralis** [comment]
@paradox41 Great, thanks!

**Pull request merged**
