### PR TITLE
Rerender the chart if the chart-options change

### PR DESCRIPTION
**Pull request by pieterjandesmedt**
As discussed in #36, this pull request adds rerendering when the chart-options change. I took a look at @rolandschuetz ' solution and his is slightly more elegant, I incorporated that in this PR as well.

### CODE REVIEW

**Comment by paradox41** [comment]
Thanks a lot!

**Comment by rolandschuetz** [comment]
Nice!

**Comment by luisfernandos** [comment]
This is not working anymore. I am trying to change the ytitle, however it does not change, because the chart.option is not checked.
Currently this fix is not in the code anymore. as you can see here:

// If chart type changed we need to recreate whole chart, otherwise we can update
    if (!this.chart || newConfig.chartType !== oldConfig.chartType) {
      this.renderChart();
    } else {
      this.chart.update(this.data, this.options);
    }


// the options should be checked if it had changed as  well.

**Comment by paradox41** [comment]
@luisfernandos what version are you on? Latest?

**Comment by luisfernandos** [comment]
the code I posted in from the latest version

**Comment by paradox41** [comment]
@luisfernandos So, tracing through the code, we see that we have a `$watch` on [chartOptions](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L25) which triggers [`update`](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L55-L70). We set the new options [here](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L59). We then check to see if we need to [rerender the whole chart](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L64), otherwise, we simply pass through the updated options and data [here](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L67) and trigger an update on the chart. Since this is part of the `else` block, it will always be executed.

So, looking at the code I don't see why it wouldn't work. 

Can you post a plunkr or something that shows the problem you are having?

**Comment by luisfernandos** [comment]
if (!this.chart || newConfig.chartType !== oldConfig.chartType) 

Here you are just checking the chartType, isn't it ?  wher are you checking for chartOptions ?

**Comment by paradox41** [comment]
I don't need to check options, the chart gets updated when the options change, not rerendered. It will always hit that `else` block so the chart will get updated with the new options.

**Comment by luisfernandos** [comment]
I have made this change in the code:
 if (!this.chart || newConfig.chartType !== oldConfig.chartType || newConfig.chartOptions !== oldConfig.chartOptions) {
                this.renderChart();
            } else {
                this.chart.update(this.data, this.options);
            }

and now it works after I chage the chartOptions.

**Comment by luisfernandos** [comment]
I am not sure if this is a specific problem, however I am using the axis plugin, and I am changing the options in order to change the axis title, so in this situation I need a render not an update. That's why it was not working for me.
I really appreciate your attention

**Comment by paradox41** [comment]
Is this related to #76

**Comment by luisfernandos** [comment]
I guess #37

**Comment by paradox41** [comment]
That is this PR. 

Are you able to post a plunkr or fiddle that demonstrates the problem for me please?

**Pull request merged**
